# -*- coding: utf-8 -*-
"""Aggregation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1coVR88SL1Jt8dQXMb_fHzb8ZWQs32qDU
"""

import numpy as np
import pandas as pd
import textwrap

df = pd.read_csv('How_Trump_Betrayed_the_General_Who_Defeated_ISIS.csv')
sentence_dict = dict(zip(list(df[df.columns[2]]), list(df[df.columns[1]])))
print(sentence_dict)

def summarize(article_id, scale, data_path, dict_path) : #article id as string, scale as number from 0 - 100 and data_path as string
  results_df = pd.read_csv(data_path)
  df = pd.read_csv(dict_path)
  sentence_dict = dict(zip(list(df[df.columns[2]]), list(df[df.columns[1]])))
  tuple_list = []

  for index, row in results_df.iterrows():
    sentence = sentence_dict[int(row['sentence_order'])]
    tuple_list.append((row['article_id'], row['sentence_order'], sentence,
                     row['agreement']))
  
  article_list = [(entry[1], entry[2], entry[3]) for entry in tuple_list if entry[0] == article_id]

  scale_list = [(entry[0], entry[1]) for entry in article_list if entry[2] >= scale]

  sorted_list = sorted(scale_list, key=lambda x: x[0])

  final_list = [entry[1] for entry in sorted_list]

  unbound_string = ' '.join(final_list)

  return textwrap.fill(unbound_string)

result = (summarize("trdl", 90, "output.csv", 'How_Trump_Betrayed_the_General_Who_Defeated_ISIS.csv'))
text_file = open("summary.txt", "w")
text_file.write(result)
text_file.close()
print(result)