# -*- coding: utf-8 -*-
"""QualityControl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nobRyxc0VasZ6LH5iNd8F4uaiSUpQoDU
"""

import numpy as np
import pandas as pd
import glob

results_df = pd.read_csv('sentences_with_votes.csv')
print(results_df.shape)
results_df.head()

from collections import Counter

counts = Counter()
maxVotes = Counter()

#columns = [col for col in results_df.columns if 'Sentence' in col]

for index, row in results_df.iterrows():
  #for col in columns: 
    is_relevant = row['is_relevant']
    sentence = (row['article_id'], row['sentence_order'], row['sentence'])
    article = row['article_id']
    #sentence = row[col]
    if is_relevant == 1:
      counts[sentence] += 1
    else:
      counts[sentence] += 0
    if counts[sentence] >= maxVotes[article]:
      maxVotes[article] = counts[sentence]

print(counts)

final_df = pd.DataFrame.from_dict(counts, orient='index')

dict_list = []

for index, row in final_df.iterrows():
  dict_list.append ( 
    {
    'article_id': row.name[0],
    'sentence_order': row.name[1],
    'sentence': row.name[2],
    'votes': row[0],
    'max_votes': maxVotes[row.name[0]],     
    'agreement': row[0] / maxVotes[row.name[0]] * 100      
    }
  )
 
transform_df = pd.DataFrame.from_dict(dict_list)

print(transform_df)

transform_df.to_csv("output.csv")