# -*- coding: utf-8 -*-
"""QualityControlModifiedInput.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-jQOQNRlP-eD_c0UxX1ECwdPHLzBA6st
"""

import numpy as np
import pandas as pd
import glob

results_df = pd.read_csv('test.csv')
print(results_df.shape)
results_df.head()

from collections import Counter

counts = Counter()
maxVotes = Counter()

columns = [col for col in results_df.columns if '.on' in col]

for index, row in results_df.iterrows():
  for col in columns: 
    is_relevant = row[col]
    sentence_order = int(row['Title'][5:]) * 28 + int(col.split('.')[1])
    article = row['Title'][:4]
    sentence = (article, sentence_order)
    if is_relevant == 1:
      counts[sentence] += 1
    else:
      counts[sentence] += 0
    if counts[sentence] >= maxVotes[article]:
      maxVotes[article] = counts[sentence]

print(counts)

final_df = pd.DataFrame.from_dict(counts, orient='index')

dict_list = []

for index, row in final_df.iterrows():
  dict_list.append ( 
    {
    'article_id': row.name[0],
    'sentence_order': row.name[1],
    'votes': row[0],
    'max_votes': maxVotes[row.name[0]],     
    'agreement': row[0] / maxVotes[row.name[0]] * 100      
    }
  )
 
transform_df = pd.DataFrame.from_dict(dict_list)

print(transform_df)

transform_df.to_csv("output.csv")