# -*- coding: utf-8 -*-
"""sectionMaker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lbq9GPYtj5ctQL1c-gCDB3mhtNsISHms
"""

import nltk
from nltk import sent_tokenize
nltk.download('punkt')
from google.colab import files

# list nums = <span style="color:Blue;"><b>①</b></span>.
# <span style="color:Blue;"><b>②</b></span>.
# <span style="color:Blue;"><b>③</b></span>.
# <span style="color:Blue;"><b>④</b></span>.
# <span style="color:Blue;"><b>⑤</b></span>.
# <span style="color:Blue;"><b>⑥</b></span>.
# <span style="color:Blue;"><b>⑦</b></span>.
# <span style="color:Blue;"><b>⑧</b></span>.
# <span style="color:Blue;"><b>⑨</b></span>.
# <span style="color:Blue;"><b>⑩</b></span>.
# <span style="color:Blue;"><b>⑪</b></span>.
# <span style="color:Blue;"><b>⑪</b></span>.
# <span style="color:Blue;"><b>⑬</b></span>.
# <span style="color:Blue;"><b>⑭</b></span>.
# <span style="color:Blue;"><b>⑮</b></span>.
# <span style="color:Blue;"><b>⑯</b></span>.
# <span style="color:Blue;"><b>⑰</b></span>.
# <span style="color:Blue;"><b>⑱</b></span>.
# <span style="color:Blue;"><b>⑲</b></span>.
# <span style="color:Blue;"><b>⑳</b></span>.

chunks = ['HTB00','HTB01','HTB02','HTB03','HTB04','HTB05','HTB06','HTB07','HTB08','HTB09','HTB10','HTB11','HTB12']

def process(chunk):
  section = ""
  count = 0
  pref = '<span style="color:Blue;"><b>'
  suf = '</b></span>.'
  nums = ['①','②','③','④','⑤','⑥','⑦','⑧','⑨','⑩','⑪','⑫','⑬','⑭','⑮','⑯','⑰','⑱','⑲','⑳']
  with open(chunk + '.txt','r') as f:
    for line in f:
      sentences = sent_tokenize(line)
      for s in sentences:
        if count < 20:
          data = s + pref + nums[count] + suf
        else:
          cnt = str(count)
          data = s + pref + nums[int(cnt[0])] + nums[int(cnt[1])] + suf
        count += 1
        section = section + data + " "

  tagged = open(chunk + "Tagged.txt","w")
  tagged.write(section)
  files.download(chunk + "Tagged.txt")
  
for chunk in chunks:
  process(chunk)
  print ('done')